add Componentization forms
Filipe-barbosa/projeto-cards pull request #3
Opened 2021-01-11 14:29 UTC by Filipe-barbosa

## Motivação

Motivado em ter um  reaproveitamento dos códigos, e evitar duplicidades  ,  foi criada a componentização do formulário de criação de cards

## Alterações 
Foi criado um novo arquivo com o nome de `Forms.js` para  receber toda a codificação e deixar o App com apenas as informações que são de sua competência

2021-01-12 16:19 UTC, marco-souza requested changes
Bom trabalho!

Fiz alguns comentários sobre boas práticas, mas num geral ta bacana! 😎

2021-01-12 16:19 UTC, marco-souza commented on src/Forms.js
> +        What needs to be done?
Já que estamos pegando o `nameButton`, acho que esse texto também poderia ser uma props tipo `formTitle`

2021-01-12 16:19 UTC, marco-souza commented on src/Forms.js
> +const Forms = (props) => (
Vamos dar um nome mais significativo para esse component/arquivo, algo tipo `AddItemForm`, dessa forma o nome reflete o que o componente faz 😉

2021-01-12 16:19 UTC, marco-souza commented on src/Forms.js
> +export default Forms
adicionar nova linha no final do arquivo

2021-01-12 16:19 UTC, marco-souza commented on src/Forms.js
> +export default Forms
Dica de leitura: https://pt.stackoverflow.com/questions/272449/por-que-inserir-uma-linha-em-branco-no-final-do-código

2021-01-12 20:23 UTC, Filipe-barbosa commented on src/Forms.js
> +const Forms = (props) => (
seria viável mudar a nomeclatura do arquivo tbm ?

2021-01-12 21:02 UTC, Filipe-barbosa commented on src/Forms.js
> +export default Forms
Então li aqui e vou adequar, otimas dicas

2021-01-13 12:15 UTC, marco-souza approved these changes
nicely done! 😄

2021-01-13 13:18 UTC, merged