Componetization task deshboard
Filipe-barbosa/projeto-cards pull request #4
Opened 2021-01-14 01:00 UTC by Filipe-barbosa

## Motivação. 

 Para finalizar a componentização da tela do projeto Cards  visando um maior dinamismo e reaproveitamento do código. 

## Alteração 

Nesta feathure  foram criados 3 arquivos o `TaskFilter`que componentiza os  botões de filtro da tela , o `TaskList` que componentiza  a área de listagem das tarefas, e por ultimo o `TasKDeshboar`, que  opera chamando esses 2 componente e monta esta parte da tela.

2021-01-14 11:11 UTC, marco-souza requested changes
Mandando bem nos React! 👍 

Deixei alguns comentários relacionados a boas práticas e legibilidade

2021-01-14 11:11 UTC, marco-souza commented on src/App.js
> +import TaskDeshboard from "./TaskDeshboard";
pequeno typo no nome, usar `TaskDashboard` com "a"

2021-01-14 11:11 UTC, marco-souza commented on src/TaskDeshboard.js
> +const TaskDeshboard = () => {
é uma boa prática adicionar uma linha em branco entre os imports e o inicio do seu código

2021-01-14 11:11 UTC, marco-souza commented on src/TaskList.js
> +const TaskList = (props) => {
Acho que esse componente não é a lista, é um `TaskItem`, a TaskList é o conjunto de TaskItems, faz sentido? Se sim, é melhor mudarmos o nome

2021-01-14 11:11 UTC, marco-souza commented on src/TaskList.js
> +            defaultChecked={props.chekboxCheked}
Acho que um nome melhor para essa props seria: `isChecked`

2021-01-14 11:11 UTC, marco-souza commented on src/TaskList.js
> +            {props.chekboxMessage}
Acho que um nome melhor para essa props seria: `itemMessage`

2021-01-14 11:11 UTC, marco-souza commented on src/TaskFilter.js
> +const TaskFilter = (props) => (
Isso não seria um filter, acho que um nome mais significativo seria: `TaskFilterButton`.

O filter seria uma função que filtra da lista

2021-01-14 11:11 UTC, marco-souza commented on src/TaskDeshboard.js
> +        {buttons.map((button) => (
Apesar de estar certo, nesse caso onde temos 3 botões, fica mais legivel colocar os 3 separadamente sabe do que usar um map.

não tem uma regra fechada, vai mais do bom senso mesmo, mas pra mim, Se os items são estáticos (não altera nem quantidade nem posição) é mais legível  escrever eles direto do que usar uma lista com um map.

2021-01-14 11:11 UTC, marco-souza commented on src/TaskDeshboard.js
> +            chekboxMessage={card.chekboxMessage}
Muito bom! 😊 
Só um ponto que é uma boa pratica em react, quanto estamos imprimindo listas no react temos que usar uma props `key` no component filho (no caso `TaskItem`), e é usado para otimizar a renderização de listas no react.

Links de referencias:
- https://pt-br.reactjs.org/docs/lists-and-keys.html
- https://pt-br.reactjs.org/docs/lists-and-keys.html#keys

2021-01-14 11:11 UTC, marco-souza commented on src/TaskDeshboard.js
> +      <h2 id="list-heading">{numTasks} tasks remaining</h2>
O component `TaskList` seria a junção desse `h2` e do `ul`, não o item da lista usado no map

2021-01-14 11:11 UTC, marco-souza commented on src/TaskDeshboard.js
> +      <div className="filters btn-group stack-exception">
O TaskFilter deveria ser essa div com os 3 botoões apenas,

2021-01-14 11:11 UTC, marco-souza commented on src/TaskList.js
> +            {props.chekboxMessage}
Na verdade seria mais interessante usar a `props.children` pra fazer isso, que na hora de usar ficaria:

```jsx
  <TaskItem isChecked={false}>
    Minha mensagem aqui
  </TaskItem>
```

https://pt-br.reactjs.org/docs/composition-vs-inheritance.html

2021-01-14 11:17 UTC, Filipe-barbosa commented on src/App.js
> +import TaskDeshboard from "./TaskDeshboard";
ok

2021-01-14 21:06 UTC, Filipe-barbosa commented on src/App.js
> +import TaskDeshboard from "./TaskDeshboard";
ok

2021-01-14 21:07 UTC, Filipe-barbosa commented on src/TaskList.js
> +const TaskList = (props) => {
ok

2021-01-14 21:07 UTC, Filipe-barbosa commented on src/TaskList.js
> +            defaultChecked={props.chekboxCheked}
ok

2021-01-19 18:41 UTC, marco-souza requested changes
Só alguns detalhes para melhorar 😉

2021-01-19 18:41 UTC, marco-souza commented on src/TaskButtonFilter.js
> +const TaskFilter = (props) => (
o nome deveria ser `TaskButtonFilter`

2021-01-19 18:41 UTC, marco-souza commented on src/TaskButtonFilter.js
> +const TaskFilter = (props) => (
o nome deveria ser `TaskButtonFilter`

2021-01-19 18:41 UTC, marco-souza commented on src/TaskItem.js
> +    <>
Não precisamos de fragment quando retornamos apenas um componente

2021-01-19 20:58 UTC, marco-souza approved these changes

2021-01-19 21:04 UTC, merged